departamentos = ("Managua","León","Granada","Masaya","Estelí","Matagalpa","Chinandega")
print("Primer departamento:", departamentos[0])
print("Último departamento:", departamentos[-1])
print("Tercer departamento:", departamentos[2])
print("Penúltimo departamento:", departamentos[-2])
print("Total de departamentos:", len(departamentos))
print("Posición de Estelí:", departamentos.index("Estelí"))